######################################
# This script defines the project pipeline - 
# it specifies the execution orders for all the code in this
# repo using a series of actions.
######################################

version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_dataset_table:
    run: ehrql:v0 generate-dataset analysis/define_dataset_table.py 
      --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz  

  # Measures - overall
  measures_overall_2018:
    run: ehrql:v0 generate-measures analysis/measures_overall.py 
      --output output/measures/measures_overall_2018.csv
      --
      --start-date "2018-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall_2018.csv

  measures_overall_2019:
    run: ehrql:v0 generate-measures analysis/measures_overall.py 
      --output output/measures/measures_overall_2019.csv
      --
      --start-date "2019-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall_2019.csv

  measures_overall_2020:
    run: ehrql:v0 generate-measures analysis/measures_overall.py 
      --output output/measures/measures_overall_2020.csv
      --
      --start-date "2020-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall_2020.csv

  measures_overall_2021:
    run: ehrql:v0 generate-measures analysis/measures_overall.py 
      --output output/measures/measures_overall_2021.csv
      --
      --start-date "2021-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall_2021.csv

  measures_overall_2022:
    run: ehrql:v0 generate-measures analysis/measures_overall.py 
      --output output/measures/measures_overall_2022.csv
      --
      --start-date "2022-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall_2022.csv
  
  # Measures - by demographic categories
  measures_demo_2018:
    run: ehrql:v0 generate-measures analysis/measures_demo.py 
      --output output/measures/measures_demo_2018.csv
      --
      --start-date "2018-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_2018.csv

  measures_demo_2019:
    run: ehrql:v0 generate-measures analysis/measures_demo.py 
      --output output/measures/measures_demo_2019.csv
      --
      --start-date "2019-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_2019.csv

  measures_demo_2020:
    run: ehrql:v0 generate-measures analysis/measures_demo.py 
      --output output/measures/measures_demo_2020.csv
      --
      --start-date "2020-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_2020.csv

  measures_demo_2021:
    run: ehrql:v0 generate-measures analysis/measures_demo.py 
      --output output/measures/measures_demo_2021.csv
      --
      --start-date "2021-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_2021.csv

  measures_demo_2022:
    run: ehrql:v0 generate-measures analysis/measures_demo.py 
      --output output/measures/measures_demo_2022.csv
      --
      --start-date "2022-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_2022.csv

  # Measures - by opioid type
  measures_type_2018:
    run: ehrql:v0 generate-measures analysis/measures_type.py 
      --output output/measures/measures_type_2018.csv
      --
      --start-date "2018-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_type_2018.csv 

  measures_type_2019:
    run: ehrql:v0 generate-measures analysis/measures_type.py 
      --output output/measures/measures_type_2019.csv
      --
      --start-date "2019-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_type_2019.csv  

  measures_type_2020:
    run: ehrql:v0 generate-measures analysis/measures_type.py 
      --output output/measures/measures_type_2020.csv
      --
      --start-date "2020-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_type_2020.csv

  measures_type_2021:
    run: ehrql:v0 generate-measures analysis/measures_type.py 
      --output output/measures/measures_type_2021.csv
      --
      --start-date "2021-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_type_2021.csv  

  measures_type_2022:
    run: ehrql:v0 generate-measures analysis/measures_type.py 
      --output output/measures/measures_type_2022.csv
      --
      --start-date "2022-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_type_2022.csv  

  # Measures - in people in care home
  measures_carehome_2018:
    run: ehrql:v0 generate-measures analysis/measures_carehome.py 
      --output output/measures/measures_carehome_2018.csv
      --
      --start-date "2018-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_carehome_2018.csv
  
  measures_carehome_2019:
    run: ehrql:v0 generate-measures analysis/measures_carehome.py 
      --output output/measures/measures_carehome_2019.csv
      --
      --start-date "2019-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_carehome_2019.csv
  
  measures_carehome_2020:
    run: ehrql:v0 generate-measures analysis/measures_carehome.py 
      --output output/measures/measures_carehome_2020.csv
      --
      --start-date "2020-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_carehome_2020.csv
  
  measures_carehome_2021:
    run: ehrql:v0 generate-measures analysis/measures_carehome.py 
      --output output/measures/measures_carehome_2021.csv
      --
      --start-date "2021-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_carehome_2021.csv
  
  measures_carehome_2022:
    run: ehrql:v0 generate-measures analysis/measures_carehome.py 
      --output output/measures/measures_carehome_2022.csv
      --
      --start-date "2022-01-01"
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_carehome_2022.csv
        
  ## Process data - time series
  process_data_ts:
   run: r:latest analysis/process/process_data_ts.R
   needs: [measures_overall_2018, measures_overall_2019, measures_overall_2020, measures_overall_2021, measures_overall_2022, 
          measures_demo_2018, measures_demo_2019, measures_demo_2020, measures_demo_2021, measures_demo_2022, 
          measures_type_2018, measures_type_2019, measures_type_2020, measures_type_2021, measures_type_2022, 
          measures_carehome_2018, measures_carehome_2019, measures_carehome_2020, measures_carehome_2021, measures_carehome_2022]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_*.csv

  ## Time series - rounding
  rounding_ts:
   run: r:latest analysis/process/rounding_ts.R
   needs: [process_data_ts]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts*.csv

  ## Process data - table
  process_data_table:
   run: r:latest analysis/process/process_data_table.R
   needs: [generate_dataset_table]
   outputs:
      highly_sensitive:
        table_csv: output/processed/final_tables.csv
      moderately_sensitive: 
        table2_csv: output/processed/final_for_tables.csv

  # ## Results table 
  # table:
  #   run: r:latest analysis/descriptive/table_stand.R
  #   needs: [process_data_table]
  #   outputs:
  #     moderately_sensitive:
  #       table: output/tables/table_*.csv

  
  # OLD COHORTEXTRACTOR CODE

  # ## Cohort data
  # generate_study_population_1:
  #   run: cohortextractor:latest generate_cohort
  #     --study-definition study_definition
  #     --index-date-range "2018-01-01 to 2018-12-01 by month" 
  #     --output-dir=output 
  #     --output-format=csv
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_*.csv

  # generate_study_population_2:
  #   run: cohortextractor:latest generate_cohort 
  #     --study-definition study_definition
  #     --index-date-range "2019-01-01 to 2019-12-01 by month" 
  #     --output-dir=output 
  #     --output-format=csv
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input*.csv

  # generate_study_population_3:
  #   run: cohortextractor:latest generate_cohort 
  #     --study-definition study_definition
  #     --index-date-range "2020-01-01 to 2020-12-01 by month" 
  #     --output-dir=output 
  #     --output-format=csv
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/inpu*.csv

  # generate_study_population_4:
  #   run: cohortextractor:latest generate_cohort 
  #     --study-definition study_definition
  #     --index-date-range "2021-01-01 to 2021-12-01 by month" 
  #     --output-dir=output 
  #     --output-format=csv
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/inp*.csv
  
  # generate_study_population_5:
  #   run: cohortextractor:latest generate_cohort 
  #     --study-definition study_definition
  #     --index-date-range "2022-01-01 to 2022-03-01 by month" 
  #     --output-dir=output 
  #     --output-format=csv
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/in*.csv

  # ## Ethnicity      
  # generate_ethnicity_cohort:
  #   run: >
  #     cohortextractor:latest generate_cohort
  #       --study-definition study_definition_ethnicity
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_ethnicity.csv


  # # Data processing ----
  
  # ## Add ethnicity
  # join_cohorts:
  #   run: >
  #     cohort-joiner:v0.0.48
  #       --lhs output/input_*.csv
  #       --rhs output/input_ethnicity.csv
  #       --output-dir output/data
  #   needs: [generate_study_population_1,  generate_study_population_2, 
  #     generate_study_population_5, generate_study_population_3, 
  #     generate_study_population_4, generate_ethnicity_cohort]
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/data/input_*.csv 


  # ## Generate measures - full population
  # generate_measures:
  #   run: >
  #     cohortextractor:latest generate_measures 
  #       --study-definition study_definition
  #       --output-dir output/data
  #   needs: [join_cohorts]
  #   outputs:
  #     moderately_sensitive:
  #       measure_csv: output/data/measure_*.csv