######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 10000

actions:

  # Extract data ----
  
  ## Cohort data
  #generate_study_population_1:
  #  run: cohortextractor:latest generate_cohort
  #    --study-definition study_definition 
  #    --index-date-range "2018-01-01 to 2018-12-01 by month" 
  #    --output-dir=output 
  #    --output-format=csv
  #  outputs:
  #    highly_sensitive:
  #      cohort: output/input_*.csv

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition 
      --index-date-range "2019-01-01 to 2019-12-01 by month" 
      --output-dir=output 
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  generate_study_population_3:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition 
      --index-date-range "2020-01-01 to 2020-12-01 by month" 
      --output-dir=output 
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv

  #generate_study_population_4:
  #  run: cohortextractor:latest generate_cohort 
  #    --study-definition study_definition 
  #    --index-date-range "2021-01-01 to 2021-12-01 by month" 
  #    --output-dir=output 
  #    --output-format=csv
  #  outputs:
  #    highly_sensitive:
  #      cohort: output/inp*.csv
  
  #generate_study_population_5:
  #  run: cohortextractor:latest generate_cohort 
  #    --study-definition study_definition 
  #    --index-date-range "2022-01-01 to 2022-03-01 by month" 
  #    --output-dir=output 
  #    --output-format=csv
  #  outputs:
  #    highly_sensitive:
  #      cohort: output/in*.csv

  ## Ethnicity      
  generate_ethnicity_cohort:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_ethnicity
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv


  # Data processing ----
  
  ## Add ethnicity
  join_cohorts:
    run: >
      cohort-joiner:v0.0.48
        --lhs output/input_*.csv
        --rhs output/input_ethnicity.csv
        --output-dir output/data
    needs: [generate_study_population_1, generate_study_population_2, 
      generate_study_population_3, generate_study_population_4, 
      generate_ethnicity_cohort]
    outputs:
      highly_sensitive:
        cohort: output/data/input_*.csv

  ## Generate measures
  generate_measures:
    run: >
      cohortextractor:latest generate_measures 
        --study-definition study_definition 
        --output-dir output/data
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        measure_csv: output/data/measure_*.csv

  ## Process data
  process_data:
   run: r:latest analysis/process/process_data.R
   needs: [generate_measures,join_cohorts]
   outputs:
      moderately_sensitive:
        measure_csv: output/joined/final_*.csv


  # Results ---

  ## Time series
  timeseries:
    run: r:latest analysis/descriptive/time_series.R
    needs: [process_data]
    outputs:
      moderately_sensitive:
        table: output/time series/timeseries_*.csv  
  
  ## Time series graphs
  graphs:
    run: r:latest analysis/descriptive/graphs.R
    needs: [timeseries]
    outputs:
      moderately_sensitive:
        plot: output/time series/graph*.png

  ## Table 
  table:
    run: r:latest analysis/descriptive/table.R
    needs: [process_data]
    outputs:
      moderately_sensitive:
        table: output/tables/table_*.csv
      

 