######################################
# This script defines the project pipeline - 
# it specifies the execution orders for all the code in this
# repo using a series of actions.
######################################


expectations:

  population_size: 10000

version: '3.0'

actions:

  generate_dataset_table:
    run: ehrql:v1 generate-dataset analysis/define_dataset_table.py 
      --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz  

  generate_dataset_missing:
    run: ehrql:v1 generate-dataset analysis/define_dataset_missing.py 
      --output output/data/dataset_missing.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_missing.csv.gz  

  # Check missing sex values
  missing:
    run: r:latest analysis/descriptive/sex_age_missing.R
    needs: [generate_dataset_missing]
    outputs:
      moderately_sensitive:
        table: output/tables/cohort_sex_age_missing.csv

  # Measures - prevalent and new prescribing - overall
  measures_overall:
    run: ehrql:v1 generate-measures analysis/measures_overall.py 
      --output output/measures/measures_overall.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall.csv

  # Measures - prevalent prescribing - by demographic categories
  measures_demo_prev:
    run: ehrql:v1 generate-measures analysis/measures_demo_prev.py 
      --output output/measures/measures_demo_prev.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_prev.csv
  
  # Measures - new prescribing - by demographic categories
  measures_demo_new:
    run: ehrql:v1 generate-measures analysis/measures_demo_new.py 
      --output output/measures/measures_demo_new.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo_new.csv

  # Measures - prevalent prescribing - by opioid type
  measures_type:
    run: ehrql:v1 generate-measures analysis/measures_type.py 
      --output output/measures/measures_type.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_type.csv 

  # Measures - prevalent and new prescribing - in people in care home
  measures_carehome:
    run: ehrql:v1 generate-measures analysis/measures_carehome.py 
      --output output/measures/measures_carehome.csv
      --
      --start-date "2018-01-01"
      --intervals 54
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_carehome.csv
        
  ## Process time series data - overall prescribing 
  process_ts_overall:
   run: r:latest analysis/process/process_ts_overall.R
   needs: [measures_overall]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_overall*.csv
 
  ## Process time series data - prescribing by demographics
  process_ts_demo:
   run: r:latest analysis/process/process_ts_demo.R
   needs: [measures_demo_prev, measures_demo_new]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_demo*.csv
  
  ## Process time series data - prescribing by admin route
  process_ts_type:
   run: r:latest analysis/process/process_ts_type.R
   needs: [measures_type]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_type*.csv
  
  ## Process time series data - prescribing to people in carehome
  process_ts_carehome:
   run: r:latest analysis/process/process_ts_carehome.R
   needs: [measures_carehome]
   outputs:
      moderately_sensitive:
        timeseries_csv: output/timeseries/ts_carehome*.csv

  ## Check time series
  figures_ts:
    run: r:latest analysis/descriptive/ts_figures.R
    needs: [process_ts_overall, process_ts_type, process_ts_carehome, process_ts_demo]
    outputs:
      moderately_sensitive:
        plots: output/descriptive/ts_plot*.png

  ## Results table 
  table:
    run: r:latest analysis/descriptive/table_stand.R
    needs: [generate_dataset_table]
    outputs:
      moderately_sensitive:
        table: output/tables/table_*.csv

  # Measures - prescribing opioids- by demographic categories
  measure_opioid_prescription_martina:
    run: ehrql:v1 generate-measures analysis/measure_opioid_prescription_martina.py --output output/measure_opioid_prescription_martina.csv.gz
    outputs:
      highly_sensitive:
        measure_csv: output/measure_opioid_prescription_martina.csv.gz